#!/usr/bin/env perl

use Mojolicious::Lite;

plugin 'write_excel';

get '/demo.xls' => sub {
    shift->render(
        handler => 'xls',
        heading => [qw(Firstname Middle LastName)],
        result  => [
            [qw(Zak B Elep)], [qw(Joel T Tanangonan)],
            [qw(Jerome S Gotangco)],
        ],
    );
};

get '/demo_without_heading.xls' => sub {
    shift->render(
        handler => 'xls',
        result =>
          [ [qw(foo bar baz)], [qw(lol wut bbq)], [qw(kick ass module)], ],
    );
};

get '/demo_with_column_width.xls' => sub {
    shift->render(
        handler => 'xls',
        result  => [],
        settings =>
          { column_width => { 'A:A' => 10, 'B:B' => 25, 'C:D' => 40 } },
    );
};

get '/demo_with_broken_column_width_1.xls' => sub {
    shift->render(
        handler  => 'xls',
        result   => [],
        settings => { column_width => undef },
    );
};

get '/demo_with_app_helper.xls' => sub {
    shift->render_xls( result =>
          [ [qw(foo bar baz)], [qw(lol wut bbq)], [qw(kick ass module)], ], );
};

app->start;
