#!/usr/bin/env perl

use Mojolicious::Lite;

plugin 'write_excel';

get '/demo.xls' => sub {
    shift->render(
        handler => 'xls',
        heading => [qw(Firstname Middle LastName)],
        result => [
            [qw(Zak B Elep)],
            [qw(Joel T Tanangonan)],
            [qw(Jerome S Gotangco)],
        ],
    );
};

get '/demo_without_heading.xls' => sub {
    shift->render(
        handler => 'xls',
        result => [
            [qw(foo bar baz)],
            [qw(lol wut bbq)],
            [qw(kick ass module)],
        ],
    );
};

app->start;
