#!/usr/bin/env perl

use Mojolicious::Lite;

plugin 'write_excel';

get '/demo.xls' => sub {
    my $self = shift;
    $self->render(
        handler => 'xls',
        heading => [qw(Firstname Middle LastName)],
        result => [
            [qw(Zak B Elep)],
            [qw(Joel T Tanangonan)],
            [qw(Jerome S Gotangco)],
        ],
    );
};

app->start;
